// Package dto provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.0 DO NOT EDIT.
package dto

// SignInJSONBody defines parameters for SignIn.
type SignInJSONBody struct {
	// Email user email
	Email *string `json:"email,omitempty"`

	// Password user password
	Password *string `json:"password,omitempty"`
}

// SignUpJSONBody defines parameters for SignUp.
type SignUpJSONBody struct {
	ConfirmPassword string `json:"confirm_password"`

	// Email valid email
	Email string `json:"email"`

	// Name full user name
	Name string `json:"name"`

	// Password strong password
	Password string `json:"password"`
}

// SignInJSONRequestBody defines body for SignIn for application/json ContentType.
type SignInJSONRequestBody SignInJSONBody

// SignUpJSONRequestBody defines body for SignUp for application/json ContentType.
type SignUpJSONRequestBody SignUpJSONBody
