Database:
  Host: localhost
  Port: 5432
  User: postgres
  Password: postgres
  Dbname: auth_db
  Sslmode: disable

DatabaseService:
  Port: 5432
  Host: localhost

Jwt:
  Secret: secretkey
  ExpiryMinutes: 5
  RefreshExpiryDays: 1
redis:
  User :
  Host :
  Port :
  Password :
  RedisAddr:
  RedisPassword:
  RedisDb: 0
  RedisDefaultdb: 0
  MinIdleConns: 200
  PoolSize: 12000
  PoolTimeout: 240
  DB: 0

server:
  AppVersion: 1.0.0
  Port: :5000
  PprofPort: :5555
  Mode: Development
  JwtSecretKey: secretkey
  CookieName: jwt-token
  ReadTimeout: 5
  WriteTimeout: 5
  SSL: true
  CtxDefaultTimeout: 12
  CSRF: true
  Debug: false
  MaxConnectionIdle: 5
  Timeout: 15
  MaxConnectionAge: 5
  Time: 120

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

postgres:
  PostgresqlHost: localhost
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: postgres
  PostgresqlDbname: auth_db
  PostgresqlSslmode: false
  PgDriver: pgx

metrics:
  Url: 0.0.0.0:7070
  ServiceName: auth_microservice

jaeger:
  Host: localhost:6831
  ServiceName: Auth_GRPC
  LogSpans: false


cookie:
  Name: jwt-token
  MaxAge: 86400
  Secure: false
  HttpOnly: true

session:
  Name: session-id
  Prefix: api-session
  Expire: 3600



