
version: '3'
services:


  postgres:
    build: ./db
    ports:
      - "5432:5432"

  app-auth:
    build: ./services/app-auth
    ports:
      - "8080:8080"

  app-db:
    build: ./services/app-db
    ports:
      - "8081:8081"