version: '3.9'

services:

  app-db:
    image: services/app-db


  app-payment:
    image: services/app-payment
    depends_on:
      - app-db
    ports:
      - "8081:80"

  app-notification:
    image: services/app-notification
    depends_on:
      - app-db
    ports:
      - "8082:80"
  app-auth:
    image: services/app-auth
    depends_on:
      - app-db
    ports:
      - "8083:80"

  app-expense:
    image: services/app-expense
    depends_on:
      - app-db
    ports:
      - "8084:80"

networks:
    default:
        name: fedhaapp

