apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-fedha-deployment
  labels:
    app: fedha
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fedha
  template:
    metadata:
      labels:
        app: fedha
    spec:
      containers:
      - name: fedha
        image: 095420225348.dkr.ecr.eu-west-1.amazonaws.com/fedha:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
